### PR TITLE
Fix: Temporarily disable requireJS if specified to load 3rd party deps

### LINKED ISSUE #528: Preview fails to load when used with RequireJS
### Environment:
- Preview version: 1.20.2, 1.20.1 and 1.19.1
- Browser name and version: Chrome V62.0.3202.94 
- Operating system and version: macOS Seirra 10.12.6

### Steps to reproduce the problem:
Code used

```javascript 
var preview = new Box.Preview();
preview.show('<file-id>', '<acess_token>', {
   container: '.preview-container',
   showDownload: true
});
```

Files were imported using cdn `https://cdn01.boxcdn.net/platform/preview/1.20.1/en-US/preview.js` and css also.

### What is the expected behavior? (Screenshots can be helpful here)
Preview for PDF file

### What went wrong? (Screenshots can be helpful here)
An icon appears with text message `PDFJS is not defined`. (Please note same code is working for an image file)

### PR DESCRIPTION
**Pull request by jeremypress**
Resolves #528

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @jeremypress has signed the CLA. Thanks for the pull request!

File: src/lib/Preview.js [hunk 1]
```diff
@@ -702,6 +702,10 @@ class Preview extends EventEmitter {
         // Optional additional query params to append to requests
         this.options.queryParams = options.queryParams || {};
 
+        // Option to pause requireJS while Preview loads third party dependencies
+        // RequireJS will be re-enabled on the 'assetsloaded' event fired by Preview
+        this.options.pauseRequireJS = !!options.pauseRequireJS;
```
Comment (jeremypress) [inline src/lib/Preview.js]: still not 100% on this name.

File: src/lib/util.js [hunk 2]
```diff
@@ -486,7 +494,21 @@ export function loadScripts(urls) {
...
-    return Promise.all(promises);
+    return Promise.all(promises)
+        .then(() => {
+            if (disableRequireJS) {
+                window.define = define;
+                window.require = require;
+                window.requirejs = requirejs;
+            }
+        })
+        .catch(() => {
```
Comment (jeremypress) [inline src/lib/util.js]: Added a catch in case we fail to load the script, we should still relinquish control over require.

File: src/lib/viewers/BaseViewer.js [hunk 3]
```diff
@@ -588,9 +588,11 @@ class BaseViewer extends EventEmitter {
      * @protected
      * @param {Array} [js] - js assets
      * @param {Array} [css] - css assets
+     * @param {boolean} [isThirdParty] is the asset to load third party
      * @return {Promise} Promise to load scripts
      */
-    loadAssets(js, css) {
+    loadAssets(js, css, isThirdParty = true) {
+        const disableRequireJS = isThirdParty && !!this.options.pauseRequireJS;
```
Comment (jeremypress) [inline src/lib/viewers/BaseViewer.js]: I added the third party boolean because we don't want to emit our message when loading annotations or any other potential code split points. These do not rely on require and should not be considered in this process.

File: src/lib/Preview.js (hunk 1 above)
Comment (JustinHoldstock) [reply src/lib/Preview.js]: `disableRequireJS`, since you've already mentioned in the comment that it `will be re-enabled on the 'assetloaded' event`?

Comment (JustinHoldstock) [reply src/lib/Preview.js]: Another argument for `disableRequireJS`, you use that term later on as parameter names

Comment (jeremypress) [reply src/lib/Preview.js]: I feel like disable means that it won't come back

Comment (tonyjin) [reply src/lib/Preview.js]: disableRequireJSWhileLoadingAssets :)

File: src/lib/viewers/BaseViewer.js (hunk 3 above)
Comment (tonyjin) [reply src/lib/viewers/BaseViewer.js]: `isViewerAsset`? I'm thinking of a future where we have 3rd party assets for annotations or other splits?

File: src/lib/util.js (hunk 2 above)
Comment (tonyjin) [reply src/lib/util.js]: Too bad we can't use `finally` yet... :(

Chrome 63/Firefox 58 is probably too new: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

File: src/lib/viewers/BaseViewer.js (hunk 3 above)
Comment (jeremypress) [reply src/lib/viewers/BaseViewer.js]: true but there are a ton of places where we are loading viewer assets, so those would all have to set a boolean

Comment (jeremypress) [reply src/lib/viewers/BaseViewer.js]: and it would also created a flipped negative `!isViewerAsset`
