### PR TITLE
Fix: Preview well-formed file in offline (fixes #793)

### LINKED ISSUE #793: [Bug] The preview of files stored on a device does not work
**Environment:**
- Preview version: 1.42.0

**Smartphone (please complete the following information):**
 - Device: iPhone, iPad
 - OS: iOS 10+
 - Browser: Hybrid applications using Cordova
 - Version: Cordova 6.5.0, Cordova-ios v.4.5.4

**Steps to reproduce the problem:**
1. Save a representation of a file to the device with all Box required metadata.
2. Try to preview this file using passed well-formed Box metadata.

**What is the expected behavior? (Screenshots can be helpful here)**
A file is previewed using the well-formed Box metadata (without calls to back-end for a file representation or related metadata)

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
Preview tries to get a file metadata from the Box server and file is not displayed.

**Link to application or sample code:**
```
  const preview = new Box.Preview();
  const boxFile = { ...the object which contains all required Box file data... };
  preview.show(boxFile, '', {
       skipServerUpdate: true,
       container: '.preview-container',
       header: 'none'
   });
```
**We intentionally do not provide token, because we want to preview a file stored on the device**

**Expected behavior**
We are expecting to have an ability to preview files stored on the device. This functionality was introduced in the [https://github.com/box/box-content-preview/pull/326](https://github.com/box/box-content-preview/pull/326)
And was available in the Preview v. 1.22.0

Thank you in advance!

### PR DESCRIPTION
**Pull request by stas-dolgachov**
Hello guys,

This pull request fixes issue - #793 
To remind you, it is required to preview well-formed files in offline mode without internet connection.
I am looking forward getting a feedback from you.

Thank you in advance

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @stas-dolgachov, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by stas-dolgachov** [comment]
CLA signed

File: src/lib/Preview.js [hunk 1]
```diff
@@ -771,10 +771,15 @@ class Preview extends EventEmitter {
             this.retryCount = 0;
         }
 
-        // Fetch access tokens before proceeding
-        getTokens(this.file.id, this.previewOptions.token)
-            .then(this.handleTokenResponse)
-            .catch(this.handleFetchError);
+        const couldPreviewOfflineWithoutToken = typeof fileIdOrFile === 'object' && this.options.skipServerUpdate;
```
Comment (DanDeMicco) [inline src/lib/Preview.js]: Can you rename this to something starting with is? maybe ```isOfflinePreview```

File: src/lib/Preview.js [hunk 2]
```diff
@@ -798,6 +803,9 @@ class Preview extends EventEmitter {
 
         // Load from cache if the current file is valid, otherwise load file info from server
         if (checkFileValid(this.file)) {
+            /* Save file in cache. This also adds the 'ORIGINAL' representation.
```
Comment (DanDeMicco) [inline src/lib/Preview.js]: Change comment style to use ```//``` instead of ```/*```

File: src/lib/__tests__/Preview-test.js [hunk 3]
```diff
@@ -1002,6 +1002,15 @@ describe('lib/Preview', () => {
             expect(preview.retryTimeout).to.equal(undefined);
         });
 
+        it('should load preview when a well-formed file object is passed and server update should be skipped', () => {
+            const previewOptions = { skipServerUpdate: true };
+            preview.parseOptions(previewOptions);
```
Comment (DanDeMicco) [inline src/lib/__tests__/Preview-test.js]: Since we are unit testing ```load```, you shouldn't call parseOptions. Instead set the required fields on the preview object

File: src/lib/Preview.js (hunk 1 above)
Comment (stas-dolgachov) [reply src/lib/Preview.js]: Thank you, done

File: src/lib/Preview.js (hunk 2 above)
Comment (stas-dolgachov) [reply src/lib/Preview.js]: Thank you, done

File: src/lib/__tests__/Preview-test.js (hunk 3 above)
Comment (stas-dolgachov) [reply src/lib/__tests__/Preview-test.js]: Thank you, done.
